apiVersion: apps/v1         #line 1  (required field) 
kind: Deployment            #line 2  (required field)
metadata:                   #line 3  (required field)
  name: project-1
  labels:                   
    app: nextjsweb          
spec:                    #line7   (required field)
  replicas: 1             #line8 How many Replica we want to create in cluster
  strategy:                 #line9
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1     #line13
  selector:
    matchLabels:
      app: nextjsweb     #line16  matching with labels name of from metadata
  template:              #line17 Templeting the Deployment and declare the spec
    metadata:
      labels:
        app: nextjsweb  #line20 matching with label name of metadata  
    spec:                #line21
      containers:
      - name: nextjsclient                                   #line23
        image: infectedshawarma/project-1:latest   #line24
        imagePullPolicy: IfNotPresent                        #line25
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000  #line31
      restartPolicy: Always    #line32