version: "4"

services:
  nextjs:
    build: .
    container_name: nextjs
    expose:
      - "3000:3000" # This makes port 3000 available to other services inside the Docker network
    environment:
      NODE_ENV: production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount the nginx.conf file
    ports:
      - "80:80"
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge # Ensures both services are connected on the same network
