version: "3"
services:
  web:
    image: vaqdocker
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - app-data:/app/data
      - ./logs:/app/logs
      - type: tmpfs
        target: /app/temp
    tmpfs:
      - /app/cache

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  app-data:
