apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "project-1.fullname" . } }
  labels: { { - include "project-1.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "project-1.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "project-1.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
