apiVersion: v1
kind: Service
metadata:
  name: { { include "project-1.fullname" . } }
  labels: { { - include "project-1.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 3000
  selector: { { - include "project-1.selectorLabels" . | nindent 4 } }
